//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_04_ISP32_SSE.db_files
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_UpdateCount
    {
        public int id_historyupdate { get; set; }
        public string name_material { get; set; }
        public Nullable<decimal> count_old { get; set; }
        public Nullable<decimal> count_new { get; set; }
    }
}
