//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_04_ISP32_SSE.db_files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Material_Produkcia = new HashSet<Material_Produkcia>();
            this.Sklads = new HashSet<Sklad>();
        }
    
        public int id_material { get; set; }
        public string name_material { get; set; }
        public string image { get; set; }
        public Nullable<decimal> ostatok { get; set; }
        public Nullable<decimal> cena { get; set; }
        public Nullable<int> id_type { get; set; }
        public string opisanie { get; set; }
        public string ed_ismer { get; set; }
        public Nullable<decimal> kol_na_sklade { get; set; }
        public Nullable<decimal> kol_v_upakovke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Produkcia> Material_Produkcia { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklads { get; set; }
    }
}
