//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_04_ISP32_SSE.db_files
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PM04_ISP32_SSE_db : DbContext
    {
        public PM04_ISP32_SSE_db()
            : base("name=PM04_ISP32_SSE_db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History_UpdateCount> History_UpdateCount { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Material_Produkcia> Material_Produkcia { get; set; }
        public virtual DbSet<Postavshik> Postavshiks { get; set; }
        public virtual DbSet<Produkcia> Produkcias { get; set; }
        public virtual DbSet<Proizvodstvo> Proizvodstvoes { get; set; }
        public virtual DbSet<Sklad> Sklads { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudniks { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Type_Produkcii> Type_Produkcii { get; set; }
    }
}
