//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_04_ISP32_SSE.db_files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkcia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkcia()
        {
            this.Material_Produkcia = new HashSet<Material_Produkcia>();
        }
    
        public int id_produkcia { get; set; }
        public string name_produkcia { get; set; }
        public int id_proizvodstvo { get; set; }
        public Nullable<int> id_type_produkcii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Produkcia> Material_Produkcia { get; set; }
        public virtual Proizvodstvo Proizvodstvo { get; set; }
        public virtual Type_Produkcii Type_Produkcii { get; set; }
    }
}
