//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_04_ISP32_SSE.db_files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int id_material { get; set; }
        public int id_postavshik { get; set; }
        public Nullable<decimal> stoimost_ed { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Postavshik Postavshik { get; set; }
    }
}
