//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_04_ISP32_SSE.db_files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int id_sotrudnik { get; set; }
        public string FIO { get; set; }
        public int id_proizvodstvo { get; set; }
    
        public virtual Proizvodstvo Proizvodstvo { get; set; }
    }
}
